const $ = (s) => document.querySelector(s);
const canvas = $('#game'), ctx = canvas.getContext('2d');
const ui = {h1:$('#health1'),h2:$('#health2'),ht1:$('#healthText1'),ht2:$('#healthText2'),timer:$('#timer'),status:$('#statusText'),hint:$('#arenaHint'),flash:$('#fightFlash'),combo:$('#comboPop'),toast:$('#toast'),mode:$('#modeLabel'),connection:$('#connectionLabel')};
const COLORS = {acid:'#d5ff45',orange:'#ff653b',blue:'#76c6ff',paper:'#f1f0eb'};
let mode='training', running=false, soundOn=false, soundCtx=null, lastTime=0, elapsed=0, roundTime=60, cameraStream=null, poseTask=null, poseBusy=false, lastPoseAt=0, lastPose=null, baseline=null, gestureEnabled=false, comboMoves=[], comboAt=0, net=null, room='', localSide=0;
let fighters=[];
const makeFighter=(x,side,name,color)=>({x,y:0,side,name,color,hp:100,guard:false,crouch:false,jump:0,move:null,moveFrame:0,flash:0,walk:0,aiAt:0,combo:0});
function resetRound(){fighters=[makeFighter(0,'left','EMBER',COLORS.acid),makeFighter(0,'right','GLACIER',COLORS.blue)];running=false;elapsed=0;roundTime=60;setHealth();ui.timer.textContent='60';ui.hint.classList.remove('hidden');ui.status.textContent='WARM UP. FIGHT WHEN READY.';$('#roundLabel').textContent='ROUND 01';}
function fitCanvas(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(r.width*d));canvas.height=Math.max(1,Math.round(r.height*d));ctx.setTransform(d,0,0,d,0,0)}
window.addEventListener('resize',fitCanvas);fitCanvas();resetRound();
function setHealth(){if(!fighters.length)return;ui.h1.style.width=`${fighters[0].hp}%`;ui.h2.style.width=`${fighters[1].hp}%`;ui.ht1.textContent=fighters[0].hp;ui.ht2.textContent=fighters[1].hp}
function toast(msg){ui.toast.textContent=msg;ui.toast.classList.add('visible');clearTimeout(toast.t);toast.t=setTimeout(()=>ui.toast.classList.remove('visible'),2200)}
function sound(freq=120,duration=.08,type='triangle'){if(!soundOn)return;try{soundCtx??=new AudioContext();const o=soundCtx.createOscillator(),g=soundCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.08,soundCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,soundCtx.currentTime+duration);o.connect(g).connect(soundCtx.destination);o.start();o.stop(soundCtx.currentTime+duration)}catch{}}
function startFight(){if(running)return;if(fighters.some(f=>f.hp<=0))resetRound();running=true;ui.hint.classList.add('hidden');ui.status.textContent='FIGHT! READ YOUR OPPONENT.';ui.connection.textContent=mode==='online'&&net?.readyState===1?'CONNECTED':'LIVE';sound(520,.12);}
function attack(f,kind='punch',hand='left',remote=false){
 if(!running||!f||f.hp<=0||f.move)return;
 const aerial=f.jump>0&&kind==='kick';const low=f.crouch&&kind==='punch';let move={kind,hand,frame:0,start:kind==='kick'?8:low?5:6,active:kind==='kick'?4:3,total:kind==='kick'?33:low?27:23,damage:kind==='kick'?(aerial?14:12):low?7:hand==='left'?6:8,range:kind==='kick'?180:150,height:low?'low':aerial?'air':'high',hit:false};f.move=move;f.moveFrame=0;
 if(!remote&&f.side==='left'){comboMoves.push(kind);comboAt=performance.now();comboMoves=comboMoves.slice(-3);if(comboMoves.join(',')==='punch,punch,kick'){f.combo=3;ui.combo.textContent='3 HIT COMBO!';ui.combo.classList.remove('show');void ui.combo.offsetWidth;ui.combo.classList.add('show');sound(610,.25,'sawtooth')}else f.combo=0;}
 if(!remote)netSend({type:'action',action:kind,hand,seq:Date.now()});
}
function hit(attacker,defender){if(mode==='online')return;const m=attacker.move;if(!m||m.hit||attacker.moveFrame<m.start||attacker.moveFrame>=m.start+m.active)return;const distance=Math.abs(attacker.x-defender.x);if(distance>m.range)return;
 if(m.height==='high'&&defender.crouch)return;if(m.height==='air'&&defender.crouch)return;
 m.hit=true;const blocked=defender.guard;const damage=blocked?Math.max(1,Math.round(m.damage*.22)):m.damage;defender.hp=Math.max(0,defender.hp-damage);defender.flash=blocked?5:11;defender.x+=(attacker.side==='left'?1:-1)*(blocked?10:26);setHealth();sound(blocked?180:85,blocked?.06:.13,blocked?'sine':'sawtooth');if(!blocked){ui.flash.classList.remove('hit');void ui.flash.offsetWidth;ui.flash.classList.add('hit');ui.status.textContent=`${attacker.name} ${m.kind==='kick'?'KICK':'STRIKE'} CONNECTS · −${damage}`;}else ui.status.textContent='BLOCKED · GOOD DEFENSE';if(defender.hp<=0){running=false;ui.status.textContent=`${attacker.name} WINS THE ROUND`;ui.hint.textContent='ROUND OVER · PRESS SPACE TO REMATCH';ui.hint.classList.remove('hidden');sound(520,.5,'sawtooth')}netSend({type:'result',damage,blocked});}
function hold(f,key,value){if(!f)return;const prop=key==='move'?'axis':key;if(f[prop]===value)return;f[prop]=value;netSend({type:'hold',key,value});}
function playerFighter(){return fighters[mode==='online'?localSide:0]}
function input(action){const f=playerFighter();if(action==='jump'){if(running&&f?.jump<=0){f.jump=35;f.crouch=false;sound(320,.08)}netSend({type:'action',action:'jump'});return}if(action==='punch'||action==='kick'){attack(f,action,action==='punch'?(Math.random()>.5?'left':'right'):'');return}if(action==='guard'||action==='crouch'){hold(f,action,true);return}if(action==='stopGuard'||action==='stopCrouch'){hold(f,action==='stopGuard'?'guard':'crouch',false)}}
const held=new Set();window.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(held.has(e.code))return;held.add(e.code);if(e.code==='Space'||e.code==='Enter')startFight();if(e.code==='KeyJ'||e.code==='KeyK')input('punch');if(e.code==='KeyL')input('kick');if(e.code==='KeyI')input('guard');if(e.code==='KeyS')input('crouch');if(e.code==='KeyW')input('jump');if(e.code==='KeyA'||e.code==='KeyD')hold(playerFighter(),'move',(held.has('KeyD')?1:0)-(held.has('KeyA')?1:0));if(mode==='local'){if(e.code==='ArrowLeft'||e.code==='ArrowRight')hold(fighters[1],'move',e.code==='ArrowLeft'?-1:1);if(e.code==='Numpad1')attack(fighters[1],'punch','left');if(e.code==='Numpad2')attack(fighters[1],'punch','right');if(e.code==='Numpad3')attack(fighters[1],'kick');if(e.code==='Numpad0')hold(fighters[1],'guard',true)}});
window.addEventListener('keyup',e=>{held.delete(e.code);if(e.code==='KeyI')input('stopGuard');if(e.code==='KeyS')input('stopCrouch');if(mode==='local'&&e.code==='Numpad0')hold(fighters[1],'guard',false);if(e.code==='KeyA'||e.code==='KeyD')hold(playerFighter(),'move',(held.has('KeyD')?1:0)-(held.has('KeyA')?1:0));if(mode==='local'&&(e.code==='ArrowLeft'||e.code==='ArrowRight'))hold(fighters[1],'move',(held.has('ArrowRight')?1:0)-(held.has('ArrowLeft')?1:0))});
function drawBackground(w,h,t){let sky=ctx.createLinearGradient(0,0,0,h);sky.addColorStop(0,'#1b2228');sky.addColorStop(.58,'#302923');sky.addColorStop(1,'#141517');ctx.fillStyle=sky;ctx.fillRect(0,0,w,h);
 // distant arena architecture
 ctx.fillStyle='#15191c';for(let i=0;i<11;i++){let x=i*w/10;let bh=h*(.2+(i%3)*.045);ctx.fillRect(x-14,h*.32-bh*.15,28,bh);ctx.fillRect(x-20,h*.32-bh*.15,40,5);}
 const glow=ctx.createRadialGradient(w*.5,h*.38,2,w*.5,h*.38,w*.49);glow.addColorStop(0,'#c16b3c28');glow.addColorStop(.52,'#be644011');glow.addColorStop(1,'transparent');ctx.fillStyle=glow;ctx.fillRect(0,0,w,h);
 // pillars and arena sigil
 ctx.globalAlpha=.24;ctx.strokeStyle='#d2a369';ctx.lineWidth=2;for(const x of [w*.08,w*.92]){ctx.beginPath();ctx.moveTo(x,h*.16);ctx.lineTo(x,h*.68);ctx.stroke();ctx.beginPath();ctx.moveTo(x-13,h*.23);ctx.lineTo(x+13,h*.23);ctx.stroke()}ctx.globalAlpha=.12;ctx.beginPath();ctx.arc(w/2,h*.56,Math.min(w,h)*.14,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(w*.36,h*.56);ctx.lineTo(w*.64,h*.56);ctx.stroke();ctx.globalAlpha=1;
 // smoky dust
 for(let i=0;i<15;i++){const x=((i*79+t*.009)%(w+70))-35,y=h*(.25+(i*37%50)/100),r=8+(i%4)*5;ctx.fillStyle=`rgba(203,141,94,${.025+Math.sin(t*.001+i)*.014})`;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()}
 let floor=h*.78;ctx.fillStyle='#18191b';ctx.fillRect(0,floor,w,h-floor);const g=ctx.createLinearGradient(0,floor,0,h);g.addColorStop(0,'#74604a');g.addColorStop(.05,'#292724');g.addColorStop(1,'#111315');ctx.fillStyle=g;ctx.fillRect(0,floor,w,h-floor);ctx.strokeStyle='#987955';ctx.globalAlpha=.24;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(0,floor);ctx.lineTo(w,floor);ctx.stroke();for(let i=0;i<9;i++){let yy=floor+(h-floor)*i/8;ctx.globalAlpha=.1-i*.009;ctx.beginPath();ctx.moveTo(0,yy);ctx.lineTo(w,yy);ctx.stroke()}ctx.globalAlpha=1;
 // embers
 for(let i=0;i<17;i++){let x=(i*97+t*.025*(i%2?1:-.5))%w,y=(h*.27+(i*41)%Math.round(h*.5)-t*.015*(i%3+1))%h;ctx.fillStyle=`rgba(255,135,70,${.24+Math.sin(t*.003+i)*.14})`;ctx.fillRect(x,y,2,2)}
}
function limb(a,b,color,width){ctx.strokeStyle='#111214';ctx.lineWidth=width+3;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(a.x+2,a.y+3);ctx.lineTo(b.x+2,b.y+3);ctx.stroke();ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.fillStyle=color;ctx.beginPath();ctx.arc(b.x,b.y,width*.47,0,Math.PI*2);ctx.fill()}
function drawFighter(f,w,h,t){let ground=h*.79,scale=Math.min(w/720,h/360),base=scale*1.03,x=f.x,y=ground-(f.jump>0?Math.sin((35-f.jump)/35*Math.PI)*h*.22:0);f.y=y;let facing=f.side==='left'?1:-1,c=f.color;
 const bob=running&&!f.crouch?Math.sin(t*.009+ (f.side==='right'?2:0))*2:0;let head={x,y:y-base*139+bob},shoulder={x:x-facing*base*2,y:y-base*104+bob},hip={x:x-facing*base*5,y:y-base*61};
 ctx.save();ctx.translate(x,y);ctx.scale(facing,1);ctx.globalAlpha=.35;ctx.fillStyle='#050606';ctx.beginPath();ctx.ellipse(0,5,base*41,base*8,0,0,Math.PI*2);ctx.fill();ctx.restore();ctx.globalAlpha=1;
 // subtle aura
 const aura=ctx.createRadialGradient(x,y-base*78,base*4,x,y-base*78,base*76);aura.addColorStop(0,c+'30');aura.addColorStop(1,'transparent');ctx.fillStyle=aura;ctx.fillRect(x-base*80,y-base*170,base*160,base*180);
 ctx.save();ctx.translate(x,y);ctx.scale(facing,1);ctx.translate(0,-(f.jump>0?Math.sin((35-f.jump)/35*Math.PI)*h*.22:0));
 let crouch=f.crouch?base*28:0;let H={x:-base*5,y:-base*61+crouch},S={x:-base*1,y:-base*103+crouch};
 // pants legs, extended kick
 let kickActive=f.move?.kind==='kick'&&f.moveFrame>=f.move.start-2&&f.moveFrame<f.move.start+f.move.active+5;let backKnee={x:-base*27,y:-base*32+crouch},backFoot={x:-base*35,y:-3+crouch},frontKnee={x:base*15,y:-base*36+crouch},frontFoot=kickActive?{x:base*91,y:-base*71+crouch}: {x:base*26,y:-3+crouch};if(f.jump>0){backFoot.y-=base*12;frontFoot.y-=base*19;}
 limb(H,backKnee,'#34363a',base*14);limb(backKnee,backFoot,'#393b40',base*11);limb(H,frontKnee,'#424448',base*15);limb(frontKnee,frontFoot,'#4a4c50',base*12);
 // torso
 ctx.fillStyle='#111214';ctx.beginPath();ctx.moveTo(S.x-base*17,S.y);ctx.lineTo(S.x+base*16,S.y);ctx.lineTo(H.x+base*19,H.y+base*9);ctx.lineTo(H.x-base*18,H.y+base*9);ctx.closePath();ctx.fill();const torso=ctx.createLinearGradient(-base*18,0,base*18,0);torso.addColorStop(0,c);torso.addColorStop(.5,c+'cc');torso.addColorStop(1,'#303236');ctx.fillStyle=torso;ctx.beginPath();ctx.moveTo(S.x-base*15,S.y);ctx.lineTo(S.x+base*15,S.y);ctx.lineTo(H.x+base*16,H.y+base*6);ctx.lineTo(H.x-base*15,H.y+base*6);ctx.closePath();ctx.fill();
 // sash and shoulder
 ctx.strokeStyle='#f1e9d1';ctx.globalAlpha=.8;ctx.lineWidth=base*4;ctx.beginPath();ctx.moveTo(S.x-base*7,S.y+base*4);ctx.lineTo(H.x+base*9,H.y+base*7);ctx.stroke();ctx.globalAlpha=1;
 // arms pose/attack
 let arm1={elbow:{x:S.x+base*25,y:S.y+base*14},hand:{x:S.x+base*38,y:S.y-base*2}},arm2={elbow:{x:S.x+base*25,y:S.y+base*31},hand:{x:S.x+base*30,y:S.y+base*44}};
 if(f.guard){arm1={elbow:{x:S.x+base*29,y:S.y-base*3},hand:{x:S.x+base*18,y:S.y-base*27}};arm2={elbow:{x:S.x+base*19,y:S.y+base*8},hand:{x:S.x+base*8,y:S.y-base*21}}}
 if(f.move?.kind==='punch'&&f.moveFrame>=f.move.start-4&&f.moveFrame<f.move.total-5){arm1={elbow:{x:S.x+base*32,y:S.y+base*3},hand:{x:S.x+base*(f.moveFrame>f.move.start?69:48),y:S.y+base*8}}}
 limb(S,arm2.elbow,'#c68960',base*9);limb(arm2.elbow,arm2.hand,c,base*10);limb(S,arm1.elbow,'#c68960',base*10);limb(arm1.elbow,arm1.hand,c,base*12);
 // head, mask, hair
 ctx.fillStyle='#bf805d';ctx.beginPath();ctx.arc(0,-base*127,base*15,0,Math.PI*2);ctx.fill();ctx.fillStyle='#181a1c';ctx.beginPath();ctx.arc(base*2,-base*132,base*16,Math.PI,Math.PI*2);ctx.lineTo(base*14,-base*123);ctx.lineTo(-base*9,-base*123);ctx.closePath();ctx.fill();ctx.fillStyle=c;ctx.fillRect(base*3,-base*127,base*12,base*4);ctx.fillStyle='#d4ab78';ctx.fillRect(base*7,-base*126,base*3,base*2);
 // belt badge
 ctx.fillStyle='#d9d0b4';ctx.fillRect(-base*5,H.y+base*3,base*12,base*5);ctx.fillStyle=c;ctx.fillRect(-base*1,H.y+base*3,base*4,base*5);
 if(f.flash>0){ctx.globalAlpha=f.flash/12*.55;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(0,-base*70,base*57,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}
 ctx.restore();
 // name strip
 ctx.fillStyle='#0e1011b8';ctx.fillRect(x-base*36,ground+9,base*72,16);ctx.fillStyle=c;ctx.font=`${base*9}px monospace`;ctx.textAlign='center';ctx.fillText(f.name,x,ground+20);
}
function aiThink(t,dt){if(mode==='local'||mode==='online')return;const cpu=fighters[1],player=fighters[0];if(!running||cpu.hp<=0)return;cpu.aiAt-=dt;if(cpu.aiAt>0)return;let dist=Math.abs(cpu.x-player.x);cpu.aiAt=450+Math.random()*500;if(player.move&&dist<190&&Math.random()<.5){cpu.guard=Math.random()<.72;setTimeout(()=>{cpu.guard=false},340);return}if(dist>205)cpu.x-=Math.sign(cpu.x-player.x)*Math.min(32,dist-190);else if(Math.random()<.68)attack(cpu,Math.random()<.62?'punch':'kick',Math.random()<.5?'left':'right');else cpu.crouch=Math.random()<.5;setTimeout(()=>cpu.crouch=false,520)}
function update(dt,t){if(!fighters.length)return;for(let i=0;i<fighters.length;i++){let f=fighters[i];if(f.move){f.moveFrame+=dt/16.67;hit(f,fighters[1-i]);if(f.moveFrame>=f.move.total)f.move=null}if(f.jump>0)f.jump=Math.max(0,f.jump-dt/16.67);if(f.flash>0)f.flash=Math.max(0,f.flash-dt/16.67);if(f.axis)f.x+=f.axis*dt*.2;f.x=Math.max(70,Math.min(canvas.clientWidth-70,f.x));}
 if(running){elapsed+=dt;roundTime=Math.max(0,60-Math.floor(elapsed/1000));ui.timer.textContent=String(roundTime).padStart(2,'0');if(roundTime<=0){running=false;let winner=fighters[0].hp===fighters[1].hp?'DRAW':fighters[0].hp>fighters[1].hp?'EMBER WINS ON TIME':'GLACIER WINS ON TIME';ui.status.textContent=winner;ui.hint.classList.remove('hidden');ui.hint.textContent='TIME UP · PRESS SPACE TO REMATCH'}aiThink(t,dt)}
 // fighters approach centerline on idle
 if(!running){const cx=canvas.clientWidth;fighters[0].x=cx*.37;fighters[1].x=cx*.63}
}
function draw(t){const w=canvas.clientWidth,h=canvas.clientHeight;if(!w||!h)return;drawBackground(w,h,t);if(fighters.length===2){drawFighter(fighters[0],w,h,t);drawFighter(fighters[1],w,h,t)}ctx.fillStyle='#ffffff12';ctx.fillRect(0,h-1,w,1)}
function loop(t){if(!lastTime)lastTime=t;let dt=Math.min(40,t-lastTime);lastTime=t;update(dt,t);draw(t);requestAnimationFrame(loop)}requestAnimationFrame(loop);

// Camera input: local inference only. The only data sent to a match server are recognized action events.
async function enableCamera(){try{cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480}},audio:false});$('#preview').srcObject=cameraStream;$('#cameraStatus').textContent='CAMERA CONNECTED · VIDEO STAYS LOCAL';$('#cameraDot').classList.add('active');$('#calibrateButton').disabled=false;$('#cameraButton').innerHTML='<span>◎</span> CAMERA READY';$('#previewMessage').textContent='CAMERA CONNECTED';toast('Camera ready. Calibrate your stance before fighting.');await loadPose();}catch(e){toast(e.name==='NotAllowedError'?'Camera permission was blocked. Keyboard controls still work.':'Could not start camera. Use HTTPS or localhost.');$('#cameraStatus').textContent='CAMERA UNAVAILABLE · KEYBOARD ACTIVE';}}
async function loadPose(){
 const version='0.10.21';
 const cdn=`https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@${version}`;
 const model='https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/1/pose_landmarker_lite.task';
 try{
  const mp=await import(`${cdn}/vision_bundle.mjs`);
  const vision=await mp.FilesetResolver.forVisionTasks(`${cdn}/wasm`);
  const options={baseOptions:{modelAssetPath:model,delegate:'GPU'},runningMode:'VIDEO',numPoses:1};
  try{poseTask=await mp.PoseLandmarker.createFromOptions(vision,options)}
  catch(gpuError){console.info('GPU pose delegate unavailable; retrying with CPU',gpuError);options.baseOptions.delegate='CPU';poseTask=await mp.PoseLandmarker.createFromOptions(vision,options)}
  requestAnimationFrame(poseLoop);$('#previewMessage').textContent='POSE TRACKING READY';
 }catch(e){console.error('Pose tracking could not load',e);const reason=(e?.message||String(e)).slice(0,110);toast(`Pose model failed to load: ${reason}`);$('#previewMessage').textContent='POSE MODEL UNAVAILABLE';$('#cameraStatus').textContent='CAMERA READY · POSE MODEL FAILED';}
}
function poseLoop(now){if(!poseTask||poseBusy)return requestAnimationFrame(poseLoop);const v=$('#preview');if(v.readyState>=2&&now-lastPoseAt>80){poseBusy=true;lastPoseAt=now;try{const res=poseTask.detectForVideo(v,now);const p=res.landmarks?.[0];if(p)processPose(p,now);drawPose(res)}catch(e){}poseBusy=false}requestAnimationFrame(poseLoop)}
function processPose(p,now){const vis=i=>(p[i]?.visibility??1)>.42;const hip=(p[23].y+p[24].y)/2,shoulder=(p[11].y+p[12].y)/2,ankles=(p[27].y+p[28].y)/2;const wristsUp= p[15].y<shoulder+.04&&p[16].y<shoulder+.04;const crouched=baseline&&hip>baseline.hip+.065;let jump=false,punch=null,kick=false;
 if(lastPose){const d=now-lastPose.t,up=lastPose.hip-hip;jump=up>.055&&d<380&&hip<lastPose.hip-.025;for(const [w,s,e,side] of [[15,11,13,'left'],[16,12,14,'right']]){const ext=Math.hypot(p[w].x-p[e].x,p[w].y-p[e].y),prev=lastPose.ext?.[side]??0;if(ext-prev>.09&&ext>.2&&vis(w)&&vis(e))punch=side}for(const [k,a,ft] of [[25,27,31],[26,28,32]]){if(vis(k)&&vis(a)&&p[a].y<p[k].y-.04&&Math.abs(p[a].y-lastPose.ankles)>.03)kick=true}}
 const ext={left:Math.hypot(p[15].x-p[13].x,p[15].y-p[13].y),right:Math.hypot(p[16].x-p[14].x,p[16].y-p[14].y)};
 if(baseline&&gestureEnabled&&running){const f=playerFighter();hold(f,'crouch',!!crouched);hold(f,'guard',!!wristsUp);if(jump)input('jump');if(punch)attack(f,'punch',punch);if(kick)attack(f,'kick')}
 if(p[15]&&p[16])lastPose={t:now,hip,ankles,ext};
 const o=$('#poseOverlay'),c=o.getContext('2d'),r=o.getBoundingClientRect(),d=devicePixelRatio||1;if(o.width!==r.width*d||o.height!==r.height*d){o.width=r.width*d;o.height=r.height*d}c.setTransform(d,0,0,d,0,0);c.clearRect(0,0,r.width,r.height);c.fillStyle=baseline?'#d5ff45':'#ff653b';for(const id of [11,12,13,14,15,16,23,24,25,26,27,28]){if(!p[id])continue;c.beginPath();c.arc((1-p[id].x)*r.width,p[id].y*r.height,3,0,Math.PI*2);c.fill()}
}
function drawPose(res){const o=$('#poseOverlay'),c=o.getContext('2d');const r=o.getBoundingClientRect(),d=devicePixelRatio||1;c.setTransform(d,0,0,d,0,0);c.clearRect(0,0,r.width,r.height);const p=res.landmarks?.[0];if(!p)return;const pairs=[[11,13],[13,15],[12,14],[14,16],[11,12],[11,23],[12,24],[23,24],[23,25],[25,27],[24,26],[26,28]];c.strokeStyle='#d5ff45';c.lineWidth=2;pairs.forEach(([a,b])=>{c.beginPath();c.moveTo((1-p[a].x)*r.width,p[a].y*r.height);c.lineTo((1-p[b].x)*r.width,p[b].y*r.height);c.stroke()});for(const id of [11,12,13,14,15,16,23,24,25,26,27,28]){c.fillStyle='#f3ffbd';c.beginPath();c.arc((1-p[id].x)*r.width,p[id].y*r.height,3,0,Math.PI*2);c.fill()}}
let calStep=0,calInterval=null;function openCalibration(){if(!cameraStream)return;$('#calibrationModal').hidden=false;calStep=0;$('#calibrationBar').style.width='0%';$('#calibrationStep').textContent='STEP 1 OF 3 · STAND NEUTRAL';$('#calibrationNext').textContent='START CALIBRATION →';}
function calibrationNext(){if(calStep===0){calStep=1;$('#calibrationNext').textContent='CAPTURE STANCE';$('#calibrationStep').textContent='STEP 1 OF 3 · STAND NEUTRAL';return}if(calStep===1){if(!lastPose){toast('Pose not detected yet. Step into the camera frame.');return}baseline={hip:lastPose.hip,ankles:lastPose.ankles};calStep=2;$('#calibrationBar').style.width='50%';$('#calibrationStep').textContent='STEP 2 OF 3 · LOWER INTO A SQUAT';$('#calibrationNext').textContent='NEXT →';return}if(calStep===2){calStep=3;$('#calibrationBar').style.width='80%';$('#calibrationStep').textContent='STEP 3 OF 3 · RAISE BOTH HANDS TO GUARD';$('#calibrationNext').textContent='FINISH CALIBRATION';return}gestureEnabled=true;$('#calibrationBar').style.width='100%';$('#calibrationStep').textContent='CALIBRATION COMPLETE · YOU’RE READY';$('#calibrationNext').textContent='ENTER THE ARENA';$('#cameraNote').textContent='Gesture controls active · local processing';$('#cameraStatus').textContent='GESTURES READY · CAMERA STAYS LOCAL';setTimeout(()=>{$('#calibrationModal').hidden=true;toast('Calibration complete. Your gestures are ready.');},450)}

function selectMode(next){mode=next;document.querySelectorAll('.mode-card').forEach(c=>c.classList.toggle('selected',c.dataset.mode===mode));$('#onlineSetup').hidden=mode!=='online';ui.mode.textContent=mode==='training'?'LOCAL TRAINING':mode==='local'?'LOCAL 2P DUEL':'ONLINE MATCH';ui.status.textContent=mode==='local'?'P1: J K L · P2: NUMPAD 1 2 3':'';}
document.querySelectorAll('.mode-card').forEach(c=>c.addEventListener('click',()=>selectMode(c.dataset.mode)));
$('#startButton').addEventListener('click',startFight);$('#cameraButton').addEventListener('click',enableCamera);$('#calibrateButton').addEventListener('click',openCalibration);$('#calibrationNext').addEventListener('click',calibrationNext);document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).hidden=true);
if(['localhost','127.0.0.1'].includes(location.hostname))$('#serverUrl').value=`ws://${location.host}`;
$('#soundToggle').addEventListener('click',e=>{soundOn=!soundOn;e.currentTarget.style.color=soundOn?'var(--acid)':'';if(soundOn)sound(440,.1)});

// WebSocket protocol: room creation/join, sequenced action and held-state messages. Combat remains server-owned.
function netSend(message){if(net?.readyState===1)net.send(JSON.stringify({...message,room,at:Date.now()}))}
$('#onlineButton').addEventListener('click',()=>{const url=$('#serverUrl').value.trim(),joinCode=$('#joinRoomCode').value.trim().toUpperCase();if(!url){toast('Add the match server address to connect.');return}try{net=new WebSocket(url);ui.connection.textContent='CONNECTING';$('#onlineButton').disabled=true;net.onopen=()=>{if(joinCode){room=joinCode;net.send(JSON.stringify({type:'join',room,name:'GLACIER'}));toast(`Joining room ${room}…`)}else{net.send(JSON.stringify({type:'create',name:'EMBER'}));toast('Creating a room…')}};net.onmessage=e=>{let m;try{m=JSON.parse(e.data)}catch{return}if(m.type==='room'){room=m.room;$('#roomCode').textContent=`ROOM ${room}`;$('#joinRoomCode').value=room;$('#onlineButton').textContent='ROOM READY';$('#onlineButton').disabled=false;toast(`Room ${room} created. Share its code with a friend.`)}if(m.type==='state'&&m.fighters){m.fighters.forEach((s,i)=>{if(fighters[i]){fighters[i].hp=s.hp;fighters[i].x=s.x;fighters[i].guard=s.guard;fighters[i].crouch=s.crouch;fighters[i].jump=s.jump||0}});setHealth()}if(m.type==='event'&&m.event==='hit'){const target=fighters[m.defender];if(target){target.hp=m.hp;setHealth()}}if(m.type==='event'&&m.event==='action'&&m.side!==localSide){const f=fighters[m.side];if(f&&m.action==='jump'){f.jump=35;f.crouch=false}else if(f)attack(f,m.action,m.hand,true)}if(m.type==='event'&&m.event==='match-ready'){localSide=m.side??localSide;ui.connection.textContent='MATCH READY';toast('Opponent connected. Start the fight!')}if(m.type==='event'&&m.event==='round-end'){running=false;ui.status.textContent=m.winner===0?'EMBER WINS THE ROUND':'GLACIER WINS THE ROUND';ui.hint.textContent='ROUND OVER · PRESS SPACE TO REMATCH';ui.hint.classList.remove('hidden')}if(m.type==='error'){toast(m.message);$('#onlineButton').disabled=false}};net.onerror=()=>toast('Could not reach that match server.');net.onclose=()=>{ui.connection.textContent='OFFLINE';$('#onlineButton').disabled=false}}catch{toast('That match server address is not valid.')}});
$('#joinRoomCode').addEventListener('input',e=>{if(!room)$('#onlineButton').textContent=e.target.value.trim()?'JOIN ROOM':'CREATE ROOM'});
window.addEventListener('beforeunload',()=>{cameraStream?.getTracks().forEach(t=>t.stop());poseTask?.close();net?.close()});
